PATH="/home/pritam/Desktop"    #path where the scripts will be generated by application
TEMPLATE="template.py"         #script template
INTERNALDB="db_control"        #table that will be created by application

HOST="localhost"
USER="root"
PASSWORD="password"
DATABASE="SharedDB"

SPECIALCHARACTER="""[!@#$%^&*_(){}[\],.?"':|<>]"""      #regex for script name